// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               unknown
// source: envoy/config/trace/v3/trace.proto

/* eslint-disable */

export const protobufPackage = "envoy.config.trace.v3";
