// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               unknown
// source: contrib/envoy/extensions/filters/network/metadata_exchange/v3/metadata_exchange.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../../../../typeRegistry";

export const protobufPackage = "envoy.tcp.metadataexchange.config";

/**
 * [#protodoc-title: MetadataExchange protocol match and data transfer]
 * MetadataExchange protocol match and data transfer
 */
export interface MetadataExchange {
  $type: "envoy.tcp.metadataexchange.config.MetadataExchange";
  /**
   * Protocol that Alpn should support on the server.
   * [#comment:TODO(GargNupur): Make it a list.]
   */
  protocol?:
    | string
    | undefined;
  /** If true, will attempt to use WDS in case the prefix peer metadata is not available. */
  enable_discovery?:
    | boolean
    | undefined;
  /**
   * Additional labels to be added to the peer metadata to help your understand the traffic.
   * e.g. ``role``, ``location`` etc.
   */
  additional_labels?: string[] | undefined;
}

function createBaseMetadataExchange(): MetadataExchange {
  return { $type: "envoy.tcp.metadataexchange.config.MetadataExchange" };
}

export const MetadataExchange: MessageFns<MetadataExchange, "envoy.tcp.metadataexchange.config.MetadataExchange"> = {
  $type: "envoy.tcp.metadataexchange.config.MetadataExchange" as const,

  encode(message: MetadataExchange, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.protocol !== undefined && message.protocol !== "") {
      writer.uint32(10).string(message.protocol);
    }
    if (message.enable_discovery !== undefined && message.enable_discovery !== false) {
      writer.uint32(16).bool(message.enable_discovery);
    }
    if (message.additional_labels !== undefined && message.additional_labels.length !== 0) {
      for (const v of message.additional_labels) {
        writer.uint32(26).string(v!);
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MetadataExchange {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMetadataExchange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.protocol = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.enable_discovery = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          if (message.additional_labels === undefined) {
            message.additional_labels = [];
          }
          const el = reader.string();
          if (el !== undefined) {
            message.additional_labels!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MetadataExchange {
    return {
      $type: MetadataExchange.$type,
      protocol: isSet(object.protocol) ? globalThis.String(object.protocol) : undefined,
      enable_discovery: isSet(object.enable_discovery) ? globalThis.Boolean(object.enable_discovery) : undefined,
      additional_labels: globalThis.Array.isArray(object?.additional_labels)
        ? object.additional_labels.map((e: any) => globalThis.String(e))
        : undefined,
    };
  },

  toJSON(message: MetadataExchange): unknown {
    const obj: any = {};
    if (message.protocol !== undefined) {
      obj.protocol = message.protocol;
    }
    if (message.enable_discovery !== undefined) {
      obj.enable_discovery = message.enable_discovery;
    }
    if (message.additional_labels?.length) {
      obj.additional_labels = message.additional_labels;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MetadataExchange>, I>>(base?: I): MetadataExchange {
    return MetadataExchange.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MetadataExchange>, I>>(object: I): MetadataExchange {
    const message = createBaseMetadataExchange();
    message.protocol = object.protocol ?? undefined;
    message.enable_discovery = object.enable_discovery ?? undefined;
    message.additional_labels = object.additional_labels?.map((e) => e) || undefined;
    return message;
  },
};

messageTypeRegistry.set(MetadataExchange.$type, MetadataExchange);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
