// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               unknown
// source: envoy/extensions/filters/http/composite/v3/composite.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../../../typeRegistry";
import { RuntimeFractionalPercent } from "../../../../../config/core/v3/base";
import { ExtensionConfigSource } from "../../../../../config/core/v3/config_source";
import { TypedExtensionConfig } from "../../../../../config/core/v3/extension";

export const protobufPackage = "envoy.extensions.filters.http.composite.v3";

/**
 * :ref:`Composite filter <config_http_filters_composite>` config. The composite filter config
 * allows delegating filter handling to another filter as determined by matching on the request
 * headers. This makes it possible to use different filters or filter configurations based on the
 * incoming request.
 *
 * This is intended to be used with
 * :ref:`ExtensionWithMatcher <envoy_v3_api_msg_extensions.common.matching.v3.ExtensionWithMatcher>`
 * where a match tree is specified that indicates (via
 * :ref:`ExecuteFilterAction <envoy_v3_api_msg_extensions.filters.http.composite.v3.ExecuteFilterAction>`)
 * which filter configuration to create and delegate to.
 */
export interface Composite {
  $type: "envoy.extensions.filters.http.composite.v3.Composite";
  /**
   * Named filter chain definitions that can be referenced from
   * :ref:`ExecuteFilterAction.filter_chain_name
   * <envoy_v3_api_field_extensions.filters.http.composite.v3.ExecuteFilterAction.filter_chain_name>`.
   * The filter chains are compiled at configuration time and can be referenced by name.
   * This is useful when the same filter chain needs to be applied across many routes,
   * as it avoids duplicating the filter chain configuration.
   */
  named_filter_chains?: Map<string, FilterChainConfiguration> | undefined;
}

export interface Composite_NamedFilterChainsEntry {
  $type: "envoy.extensions.filters.http.composite.v3.Composite.NamedFilterChainsEntry";
  key: string;
  value?: FilterChainConfiguration | undefined;
}

/**
 * A list of filter configurations to be called in order. Note that this can be used as the type
 * inside of an ECDS :ref:`TypedExtensionConfig
 * <envoy_v3_api_msg_config.core.v3.TypedExtensionConfig>` extension, which allows a chain of
 * filters to be configured dynamically. In that case, the types of all filters in the chain must
 * be present in the :ref:`ExtensionConfigSource.type_urls
 * <envoy_v3_api_field_config.core.v3.ExtensionConfigSource.type_urls>` field.
 */
export interface FilterChainConfiguration {
  $type: "envoy.extensions.filters.http.composite.v3.FilterChainConfiguration";
  typed_config?: TypedExtensionConfig[] | undefined;
}

/** Configuration for an extension configuration discovery service with name. */
export interface DynamicConfig {
  $type: "envoy.extensions.filters.http.composite.v3.DynamicConfig";
  /**
   * The name of the extension configuration. It also serves as a resource name in ExtensionConfigDS.
   * The resource type in the ``DiscoveryRequest`` will be :ref:`TypedExtensionConfig
   * <envoy_v3_api_msg_config.core.v3.TypedExtensionConfig>`.
   */
  name?:
    | string
    | undefined;
  /**
   * Configuration source specifier for an extension configuration discovery
   * service. In case of a failure and without the default configuration,
   * 500(Internal Server Error) will be returned.
   */
  config_discovery?: ExtensionConfigSource | undefined;
}

/**
 * Composite match action (see :ref:`matching docs <arch_overview_matching_api>` for more info on match actions).
 * This specifies the filter configuration of the filter that the composite filter should delegate filter interactions to.
 * [#next-free-field: 6]
 */
export interface ExecuteFilterAction {
  $type: "envoy.extensions.filters.http.composite.v3.ExecuteFilterAction";
  /**
   * Filter specific configuration which depends on the filter being
   * instantiated. See the supported filters for further documentation.
   * Only one of ``typed_config``, ``dynamic_config``, ``filter_chain``, or ``filter_chain_name``
   * can be set.
   * [#extension-category: envoy.filters.http]
   */
  typed_config?:
    | TypedExtensionConfig
    | undefined;
  /**
   * Dynamic configuration of filter obtained via extension configuration discovery service.
   * Only one of ``typed_config``, ``dynamic_config``, ``filter_chain``, or ``filter_chain_name``
   * can be set.
   */
  dynamic_config?:
    | DynamicConfig
    | undefined;
  /**
   * An inlined list of filter configurations. The specified filters will be executed in order.
   * Only one of ``typed_config``, ``dynamic_config``, ``filter_chain``, or ``filter_chain_name``
   * can be set.
   */
  filter_chain?:
    | FilterChainConfiguration
    | undefined;
  /**
   * The name of a filter chain defined in
   * :ref:`Composite.named_filter_chains
   * <envoy_v3_api_field_extensions.filters.http.composite.v3.Composite.named_filter_chains>`.
   * At runtime, if the named filter chain is not found in the Composite filter's configuration,
   * no filter will be applied for this match (the action is silently skipped).
   * Only one of ``typed_config``, ``dynamic_config``, ``filter_chain``, or ``filter_chain_name``
   * can be set.
   */
  filter_chain_name?:
    | string
    | undefined;
  /**
   * Probability of the action execution. If not specified, this is 100%.
   * This allows sampling behavior for the configured actions.
   * For example, if
   * :ref:`default_value <envoy_v3_api_field_config.core.v3.RuntimeFractionalPercent.default_value>`
   * under the ``sample_percent`` is configured with 30%, a dice roll with that
   * probability is done. The underline action will only be executed if the
   * dice roll returns positive. Otherwise, the action is skipped.
   */
  sample_percent?: RuntimeFractionalPercent | undefined;
}

function createBaseComposite(): Composite {
  return { $type: "envoy.extensions.filters.http.composite.v3.Composite" };
}

export const Composite: MessageFns<Composite, "envoy.extensions.filters.http.composite.v3.Composite"> = {
  $type: "envoy.extensions.filters.http.composite.v3.Composite" as const,

  encode(message: Composite, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    (message.named_filter_chains || new Map()).forEach((value, key) => {
      Composite_NamedFilterChainsEntry.encode({
        $type: "envoy.extensions.filters.http.composite.v3.Composite.NamedFilterChainsEntry",
        key: key as any,
        value,
      }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Composite {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComposite();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = Composite_NamedFilterChainsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            if (message.named_filter_chains === undefined) {
              message.named_filter_chains = new Map();
            }
            message.named_filter_chains!.set(entry1.key, entry1.value);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Composite {
    return {
      $type: Composite.$type,
      named_filter_chains: isObject(object.named_filter_chains)
        ? Object.entries(object.named_filter_chains).reduce<Map<string, FilterChainConfiguration>>(
          (acc, [key, value]) => {
            acc.set(key, FilterChainConfiguration.fromJSON(value));
            return acc;
          },
          new Map(),
        )
        : undefined,
    };
  },

  toJSON(message: Composite): unknown {
    const obj: any = {};
    if (message.named_filter_chains?.size) {
      obj.named_filter_chains = {};
      message.named_filter_chains.forEach((v, k) => {
        obj.named_filter_chains[k] = FilterChainConfiguration.toJSON(v);
      });
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Composite>, I>>(base?: I): Composite {
    return Composite.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Composite>, I>>(object: I): Composite {
    const message = createBaseComposite();
    message.named_filter_chains = (object.named_filter_chains === undefined || object.named_filter_chains === null)
      ? undefined
      : (() => {
        const m = new Map();
        (object.named_filter_chains as Map<string, FilterChainConfiguration> ?? new Map()).forEach((value, key) => {
          if (value !== undefined) {
            m.set(key, FilterChainConfiguration.fromPartial(value));
          }
        });
        return m;
      })();
    return message;
  },
};

messageTypeRegistry.set(Composite.$type, Composite);

function createBaseComposite_NamedFilterChainsEntry(): Composite_NamedFilterChainsEntry {
  return { $type: "envoy.extensions.filters.http.composite.v3.Composite.NamedFilterChainsEntry", key: "" };
}

export const Composite_NamedFilterChainsEntry: MessageFns<
  Composite_NamedFilterChainsEntry,
  "envoy.extensions.filters.http.composite.v3.Composite.NamedFilterChainsEntry"
> = {
  $type: "envoy.extensions.filters.http.composite.v3.Composite.NamedFilterChainsEntry" as const,

  encode(message: Composite_NamedFilterChainsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== undefined) {
      FilterChainConfiguration.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Composite_NamedFilterChainsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseComposite_NamedFilterChainsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = FilterChainConfiguration.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Composite_NamedFilterChainsEntry {
    return {
      $type: Composite_NamedFilterChainsEntry.$type,
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? FilterChainConfiguration.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: Composite_NamedFilterChainsEntry): unknown {
    const obj: any = {};
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.value !== undefined) {
      obj.value = FilterChainConfiguration.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Composite_NamedFilterChainsEntry>, I>>(
    base?: I,
  ): Composite_NamedFilterChainsEntry {
    return Composite_NamedFilterChainsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Composite_NamedFilterChainsEntry>, I>>(
    object: I,
  ): Composite_NamedFilterChainsEntry {
    const message = createBaseComposite_NamedFilterChainsEntry();
    message.key = object.key ?? "";
    message.value = (object.value !== undefined && object.value !== null)
      ? FilterChainConfiguration.fromPartial(object.value)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(Composite_NamedFilterChainsEntry.$type, Composite_NamedFilterChainsEntry);

function createBaseFilterChainConfiguration(): FilterChainConfiguration {
  return { $type: "envoy.extensions.filters.http.composite.v3.FilterChainConfiguration" };
}

export const FilterChainConfiguration: MessageFns<
  FilterChainConfiguration,
  "envoy.extensions.filters.http.composite.v3.FilterChainConfiguration"
> = {
  $type: "envoy.extensions.filters.http.composite.v3.FilterChainConfiguration" as const,

  encode(message: FilterChainConfiguration, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.typed_config !== undefined && message.typed_config.length !== 0) {
      for (const v of message.typed_config) {
        TypedExtensionConfig.encode(v!, writer.uint32(10).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FilterChainConfiguration {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilterChainConfiguration();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          if (message.typed_config === undefined) {
            message.typed_config = [];
          }
          const el = TypedExtensionConfig.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.typed_config!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FilterChainConfiguration {
    return {
      $type: FilterChainConfiguration.$type,
      typed_config: globalThis.Array.isArray(object?.typed_config)
        ? object.typed_config.map((e: any) => TypedExtensionConfig.fromJSON(e))
        : undefined,
    };
  },

  toJSON(message: FilterChainConfiguration): unknown {
    const obj: any = {};
    if (message.typed_config?.length) {
      obj.typed_config = message.typed_config.map((e) => TypedExtensionConfig.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FilterChainConfiguration>, I>>(base?: I): FilterChainConfiguration {
    return FilterChainConfiguration.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FilterChainConfiguration>, I>>(object: I): FilterChainConfiguration {
    const message = createBaseFilterChainConfiguration();
    message.typed_config = object.typed_config?.map((e) => TypedExtensionConfig.fromPartial(e)) || undefined;
    return message;
  },
};

messageTypeRegistry.set(FilterChainConfiguration.$type, FilterChainConfiguration);

function createBaseDynamicConfig(): DynamicConfig {
  return { $type: "envoy.extensions.filters.http.composite.v3.DynamicConfig" };
}

export const DynamicConfig: MessageFns<DynamicConfig, "envoy.extensions.filters.http.composite.v3.DynamicConfig"> = {
  $type: "envoy.extensions.filters.http.composite.v3.DynamicConfig" as const,

  encode(message: DynamicConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== undefined && message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.config_discovery !== undefined) {
      ExtensionConfigSource.encode(message.config_discovery, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DynamicConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDynamicConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.config_discovery = ExtensionConfigSource.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DynamicConfig {
    return {
      $type: DynamicConfig.$type,
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      config_discovery: isSet(object.config_discovery)
        ? ExtensionConfigSource.fromJSON(object.config_discovery)
        : undefined,
    };
  },

  toJSON(message: DynamicConfig): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.config_discovery !== undefined) {
      obj.config_discovery = ExtensionConfigSource.toJSON(message.config_discovery);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DynamicConfig>, I>>(base?: I): DynamicConfig {
    return DynamicConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DynamicConfig>, I>>(object: I): DynamicConfig {
    const message = createBaseDynamicConfig();
    message.name = object.name ?? undefined;
    message.config_discovery = (object.config_discovery !== undefined && object.config_discovery !== null)
      ? ExtensionConfigSource.fromPartial(object.config_discovery)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(DynamicConfig.$type, DynamicConfig);

function createBaseExecuteFilterAction(): ExecuteFilterAction {
  return { $type: "envoy.extensions.filters.http.composite.v3.ExecuteFilterAction" };
}

export const ExecuteFilterAction: MessageFns<
  ExecuteFilterAction,
  "envoy.extensions.filters.http.composite.v3.ExecuteFilterAction"
> = {
  $type: "envoy.extensions.filters.http.composite.v3.ExecuteFilterAction" as const,

  encode(message: ExecuteFilterAction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.typed_config !== undefined) {
      TypedExtensionConfig.encode(message.typed_config, writer.uint32(10).fork()).join();
    }
    if (message.dynamic_config !== undefined) {
      DynamicConfig.encode(message.dynamic_config, writer.uint32(18).fork()).join();
    }
    if (message.filter_chain !== undefined) {
      FilterChainConfiguration.encode(message.filter_chain, writer.uint32(34).fork()).join();
    }
    if (message.filter_chain_name !== undefined && message.filter_chain_name !== "") {
      writer.uint32(42).string(message.filter_chain_name);
    }
    if (message.sample_percent !== undefined) {
      RuntimeFractionalPercent.encode(message.sample_percent, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExecuteFilterAction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExecuteFilterAction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.typed_config = TypedExtensionConfig.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.dynamic_config = DynamicConfig.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.filter_chain = FilterChainConfiguration.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.filter_chain_name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.sample_percent = RuntimeFractionalPercent.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExecuteFilterAction {
    return {
      $type: ExecuteFilterAction.$type,
      typed_config: isSet(object.typed_config) ? TypedExtensionConfig.fromJSON(object.typed_config) : undefined,
      dynamic_config: isSet(object.dynamic_config) ? DynamicConfig.fromJSON(object.dynamic_config) : undefined,
      filter_chain: isSet(object.filter_chain) ? FilterChainConfiguration.fromJSON(object.filter_chain) : undefined,
      filter_chain_name: isSet(object.filter_chain_name) ? globalThis.String(object.filter_chain_name) : undefined,
      sample_percent: isSet(object.sample_percent)
        ? RuntimeFractionalPercent.fromJSON(object.sample_percent)
        : undefined,
    };
  },

  toJSON(message: ExecuteFilterAction): unknown {
    const obj: any = {};
    if (message.typed_config !== undefined) {
      obj.typed_config = TypedExtensionConfig.toJSON(message.typed_config);
    }
    if (message.dynamic_config !== undefined) {
      obj.dynamic_config = DynamicConfig.toJSON(message.dynamic_config);
    }
    if (message.filter_chain !== undefined) {
      obj.filter_chain = FilterChainConfiguration.toJSON(message.filter_chain);
    }
    if (message.filter_chain_name !== undefined) {
      obj.filter_chain_name = message.filter_chain_name;
    }
    if (message.sample_percent !== undefined) {
      obj.sample_percent = RuntimeFractionalPercent.toJSON(message.sample_percent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExecuteFilterAction>, I>>(base?: I): ExecuteFilterAction {
    return ExecuteFilterAction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExecuteFilterAction>, I>>(object: I): ExecuteFilterAction {
    const message = createBaseExecuteFilterAction();
    message.typed_config = (object.typed_config !== undefined && object.typed_config !== null)
      ? TypedExtensionConfig.fromPartial(object.typed_config)
      : undefined;
    message.dynamic_config = (object.dynamic_config !== undefined && object.dynamic_config !== null)
      ? DynamicConfig.fromPartial(object.dynamic_config)
      : undefined;
    message.filter_chain = (object.filter_chain !== undefined && object.filter_chain !== null)
      ? FilterChainConfiguration.fromPartial(object.filter_chain)
      : undefined;
    message.filter_chain_name = object.filter_chain_name ?? undefined;
    message.sample_percent = (object.sample_percent !== undefined && object.sample_percent !== null)
      ? RuntimeFractionalPercent.fromPartial(object.sample_percent)
      : undefined;
    return message;
  },
};

messageTypeRegistry.set(ExecuteFilterAction.$type, ExecuteFilterAction);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
