// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               unknown
// source: envoy/extensions/http/cache_v2/simple_http_cache/v3/config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../../../typeRegistry";

export const protobufPackage = "envoy.extensions.http.cache_v2.simple_http_cache.v3";

/** [#extension: envoy.extensions.http.cache_v2.simple] */
export interface SimpleHttpCacheV2Config {
  $type: "envoy.extensions.http.cache_v2.simple_http_cache.v3.SimpleHttpCacheV2Config";
}

function createBaseSimpleHttpCacheV2Config(): SimpleHttpCacheV2Config {
  return { $type: "envoy.extensions.http.cache_v2.simple_http_cache.v3.SimpleHttpCacheV2Config" };
}

export const SimpleHttpCacheV2Config: MessageFns<
  SimpleHttpCacheV2Config,
  "envoy.extensions.http.cache_v2.simple_http_cache.v3.SimpleHttpCacheV2Config"
> = {
  $type: "envoy.extensions.http.cache_v2.simple_http_cache.v3.SimpleHttpCacheV2Config" as const,

  encode(_: SimpleHttpCacheV2Config, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SimpleHttpCacheV2Config {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSimpleHttpCacheV2Config();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): SimpleHttpCacheV2Config {
    return { $type: SimpleHttpCacheV2Config.$type };
  },

  toJSON(_: SimpleHttpCacheV2Config): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<SimpleHttpCacheV2Config>, I>>(base?: I): SimpleHttpCacheV2Config {
    return SimpleHttpCacheV2Config.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SimpleHttpCacheV2Config>, I>>(_: I): SimpleHttpCacheV2Config {
    const message = createBaseSimpleHttpCacheV2Config();
    return message;
  },
};

messageTypeRegistry.set(SimpleHttpCacheV2Config.$type, SimpleHttpCacheV2Config);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
