// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.2.7
//   protoc               unknown
// source: envoy/api/v2/core/event_service_config.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { messageTypeRegistry } from "../../../../typeRegistry";
import { GrpcService } from "./grpc_service";

export const protobufPackage = "envoy.api.v2.core";

/**
 * [#not-implemented-hide:]
 * Configuration of the event reporting service endpoint.
 */
export interface EventServiceConfig {
  $type: "envoy.api.v2.core.EventServiceConfig";
  config_source_specifier?:
    | //
    /** Specifies the gRPC service that hosts the event reporting service. */
    { $case: "grpc_service"; grpc_service: GrpcService }
    | undefined;
}

function createBaseEventServiceConfig(): EventServiceConfig {
  return { $type: "envoy.api.v2.core.EventServiceConfig", config_source_specifier: undefined };
}

export const EventServiceConfig: MessageFns<EventServiceConfig, "envoy.api.v2.core.EventServiceConfig"> = {
  $type: "envoy.api.v2.core.EventServiceConfig" as const,

  encode(message: EventServiceConfig, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    switch (message.config_source_specifier?.$case) {
      case "grpc_service":
        GrpcService.encode(message.config_source_specifier.grpc_service, writer.uint32(10).fork()).join();
        break;
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): EventServiceConfig {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEventServiceConfig();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.config_source_specifier = {
            $case: "grpc_service",
            grpc_service: GrpcService.decode(reader, reader.uint32()),
          };
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): EventServiceConfig {
    return {
      $type: EventServiceConfig.$type,
      config_source_specifier: isSet(object.grpc_service)
        ? { $case: "grpc_service", grpc_service: GrpcService.fromJSON(object.grpc_service) }
        : undefined,
    };
  },

  toJSON(message: EventServiceConfig): unknown {
    const obj: any = {};
    if (message.config_source_specifier?.$case === "grpc_service") {
      obj.grpc_service = GrpcService.toJSON(message.config_source_specifier.grpc_service);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<EventServiceConfig>, I>>(base?: I): EventServiceConfig {
    return EventServiceConfig.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<EventServiceConfig>, I>>(object: I): EventServiceConfig {
    const message = createBaseEventServiceConfig();
    if (
      object.config_source_specifier?.$case === "grpc_service" &&
      object.config_source_specifier?.grpc_service !== undefined &&
      object.config_source_specifier?.grpc_service !== null
    ) {
      message.config_source_specifier = {
        $case: "grpc_service",
        grpc_service: GrpcService.fromPartial(object.config_source_specifier.grpc_service),
      };
    }
    return message;
  },
};

messageTypeRegistry.set(EventServiceConfig.$type, EventServiceConfig);

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in Exclude<keyof T, "$type">]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P> | "$type">]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T, V extends string> {
  readonly $type: V;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
